baseURL = "//maxofbritton.com/makingwithmax/"
languageCode = "en-us"
title = "Making with Max"
theme = "cactus"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  
# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Recipies"
url = "/recipies"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3


[params]

  colortheme = "dark" # dark, light, white, or classic

  description = """
    This is a website filled with the things I like to make - mostly food."""

  mainSection = "recipies"

  tagsOverview = false
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/maxofbritton" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = false # default